Repository jenkinsci/email-ext-plugin, pull requests merged in 2020-11, with the labels that each got.

#255 Minor test cleanup
  src/test/java/hudson/plugins/emailext/AttachmentUtilsTest.java
  src/test/java/hudson/plugins/emailext/EmailExtStepTest.java
  src/test/java/hudson/plugins/emailext/ExtendedEmailPublisherMatrixTest.java
  src/test/java/hudson/plugins/emailext/ExtendedEmailPublisherTest.java
  src/test/java/hudson/plugins/emailext/plugins/RecipientProviderTest.java
  src/test/java/hudson/plugins/emailext/plugins/content/TriggerNameContentTest.java
  src/test/java/hudson/plugins/emailext/plugins/recipients/UpstreamComitterRecipientProviderTest.java
  src/test/java/hudson/plugins/emailext/plugins/trigger/AbstractScriptTriggerTest.java
  src/test/java/hudson/plugins/emailext/recipients/EmailRecipientUtilsTest.java
Labels: skip-changelog

#256 [JENKINS-63522] Debug logs are incomplete when From address is invalid
  src/main/java/hudson/plugins/emailext/ExtendedEmailPublisher.java
Labels: bug

#257 Use Functions.printStackTrace where possible
  src/main/java/hudson/plugins/emailext/ExtendedEmailPublisher.java
  src/main/java/hudson/plugins/emailext/plugins/content/ScriptContent.java
  src/main/java/hudson/plugins/emailext/plugins/trigger/AbstractScriptTrigger.java
  src/test/java/hudson/plugins/emailext/ExtendedEmailPublisherTest.java
Labels: internal

#258 Add additional debug logging when valid mail account cannot be found
  src/main/java/hudson/plugins/emailext/ExtendedEmailPublisher.java
  src/main/java/hudson/plugins/emailext/ExtendedEmailPublisherDescriptor.java
  src/main/java/hudson/plugins/emailext/MailAccount.java
  src/test/java/hudson/plugins/emailext/ExtendedEmailPublisherDescriptorTest.java
  src/test/java/hudson/plugins/emailext/ExtendedEmailPublisherTest.java
Labels: bug

#259 Add test for Project From
  src/test/java/hudson/plugins/emailext/ExtendedEmailPublisherTest.java
Labels: tests

#262 [JENKINS-64141] Restore localhost as default SMTP server
  src/main/java/hudson/plugins/emailext/MailAccount.java
  src/test/java/hudson/plugins/emailext/AttachmentUtilsTest.java
  src/test/java/hudson/plugins/emailext/EmailExtStepTest.java
  src/test/java/hudson/plugins/emailext/ExtendedEmailPublisherMatrixTest.java
  src/test/java/hudson/plugins/emailext/ExtendedEmailPublisherTest.java
  src/test/java/hudson/plugins/emailext/plugins/content/ScriptContentSecureTest.java
  src/test/java/hudson/plugins/emailext/plugins/content/ScriptContentTest.java
  src/test/java/hudson/plugins/emailext/plugins/content/TriggerNameContentTest.java
  src/test/java/hudson/plugins/emailext/plugins/recipients/UpstreamComitterRecipientProviderTest.java
Labels: bug
