Repository jenkinsci/email-ext-plugin, pull requests merged in 2024-11, with the labels that each got.

#555 JENKINS-73740: Allow admins to disable throttling
  src/main/java/hudson/plugins/emailext/ExtendedEmailPublisher.java
  src/main/java/hudson/plugins/emailext/ExtendedEmailPublisherDescriptor.java
  src/main/resources/hudson/plugins/emailext/ExtendedEmailPublisher/global.groovy
  src/main/webapp/help/globalConfig/throttlingEnabled.html
  src/test/java/hudson/plugins/emailext/ExtendedEmailPublisherTest.java
Labels: bug

#557 Require Java 17
  pom.xml
  src/main/java/hudson/plugins/emailext/AttachmentUtils.java
  src/main/java/hudson/plugins/emailext/EmailRecipientUtils.java
  src/main/java/hudson/plugins/emailext/ExtendedEmailPublisher.java
  src/main/java/hudson/plugins/emailext/ExtendedEmailPublisherContext.java
  src/main/java/hudson/plugins/emailext/MailAccount.java
  src/main/java/hudson/plugins/emailext/groovy/sandbox/EmailExtScriptTokenMacroWhitelist.java
  src/main/java/hudson/plugins/emailext/plugins/EmailTrigger.java
  src/main/java/hudson/plugins/emailext/plugins/EmailTriggerDescriptor.java
  src/main/java/hudson/plugins/emailext/plugins/content/AbstractEvalContent.java
  src/main/java/hudson/plugins/emailext/plugins/content/EmailExtScript.java
  src/main/java/hudson/plugins/emailext/plugins/content/FailedTestsContent.java
  src/main/java/hudson/plugins/emailext/plugins/content/ScriptContentBuildWrapper.java
  src/main/java/hudson/plugins/emailext/plugins/recipients/CulpritsRecipientProvider.java
  src/main/java/hudson/plugins/emailext/plugins/recipients/PreviousRecipientProvider.java
  src/main/java/hudson/plugins/emailext/plugins/recipients/RecipientProviderUtilities.java
  src/main/java/hudson/plugins/emailext/plugins/recipients/UpstreamComitterRecipientProvider.java
  src/main/java/hudson/plugins/emailext/plugins/trigger/AbstractScriptTrigger.java
  src/main/java/hudson/plugins/emailext/plugins/trigger/PreBuildScriptTrigger.java
  src/main/java/hudson/plugins/emailext/plugins/trigger/ScriptTrigger.java
  src/main/java/hudson/plugins/emailext/watching/EmailExtWatchAction.java
  src/test/java/hudson/plugins/emailext/AttachmentUtilsTest.java
  src/test/java/hudson/plugins/emailext/EmailExtStepTest.java
  src/test/java/hudson/plugins/emailext/ExtendedEmailPublisherTest.java
  src/test/java/hudson/plugins/emailext/plugins/CssInlinerTest.java
  src/test/java/hudson/plugins/emailext/plugins/content/FailedTestsContentTest.java
  src/test/java/hudson/plugins/emailext/plugins/content/JellyScriptContentTest.java
  src/test/java/hudson/plugins/emailext/plugins/content/ScriptContentSecureTest.java
  src/test/java/hudson/plugins/emailext/plugins/trigger/AbstractScriptTriggerTest.java
Labels: enhancement

#560 Migrate to Jakarta EE 9
  src/main/java/hudson/plugins/emailext/ExtendedEmailPublisher.java
  src/main/java/hudson/plugins/emailext/ExtendedEmailPublisherDescriptor.java
  src/main/java/hudson/plugins/emailext/plugins/EmailTrigger.java
  src/main/java/hudson/plugins/emailext/plugins/trigger/AbstractScriptTrigger.java
  src/main/java/hudson/plugins/emailext/watching/EmailExtWatchAction.java
  src/main/java/hudson/plugins/emailext/watching/EmailExtWatchJobProperty.java
  src/test/java/hudson/plugins/emailext/ExtendedEmailPublisherTest.java
Labels: internal

#561 fix: prevent watching from applying to all jobs
  src/main/java/hudson/plugins/emailext/ExtendedEmailPublisher.java
  src/main/java/hudson/plugins/emailext/watching/EmailExtWatchAction.java
  src/main/java/hudson/plugins/emailext/watching/EmailExtWatchJobProperty.java
  src/main/resources/hudson/plugins/emailext/watching/EmailExtWatchAction/index.groovy
Labels: bug
